server:
  port: 9001

spring:
  application:
    name: game-service
  data:
    mongodb:
      uri: mongodb+srv://duong:17112003@ktpm.syri56f.mongodb.net/<KTPM>?retryWrites=true&w=majority&appName=KTPM


jwt:
  secret: BvPHGM8C0ia4uOuxxqPD5DTbWC9F9TWvPStp3pb7ARo0oK2mJ3pd3YG4lxA9i8bj6OTbadwezxgeEByY
  expiration: 86400