version: '5'
services:
  db:
    image: postgres
    environment:
      POSTGRES_PASSWORD: 123
      POSTGRES_USER: postgres
      POSTGRES_DB: db
    ports:
      - 5432:5432
  redis:
    image: redis
    ports:
      - "6379:6379"