export const CREATE_GAME_REQUEST = 'CREATE_GAME_REQUEST';
export const CREATE_GAME_SUCCESS = 'CREATE_GAME_SUCCESS';
export const CREATE_GAME_FAILURE = 'CREATE_GAME_FAILURE';

export const GET_ALL_GAME_REQUEST = 'GET_ALL_GAME_REQUEST';
export const GET_ALL_GAME_SUCCESS = 'GET_ALL_GAME_SUCCESS';
export const GET_ALL_GAME_FAILURE = 'GET_ALL_GAME_FAILURE';

export const DELETE_GAME_REQUEST = 'DELETE_GAME_REQUEST';
export const DELETE_GAME_SUCCESS = 'DELETE_GAME_SUCCESS';
export const DELETE_GAME_FAILURE = 'DELETE_GAME_FAILURE';

export const SEARCH_GAME_REQUEST = 'SEARCH_GAME_REQUEST';
export const SEARCH_GAME_SUCCESS = 'SEARCH_GAME_SUCCESS';
export const SEARCH_GAME_FAILURE = 'SEARCH_GAME_FAILURE';

export const UPDATE_GAMES_AVAILABILITY_REQUEST = 'UPDATE_GAMES_AVAILABILITY_REQUEST';
export const UPDATE_GAMES_AVAILABILITY_SUCCESS = 'UPDATE_GAMES_AVAILABILITY_SUCCESS';
export const UPDATE_GAMES_AVAILABILITY_FAILURE = 'UPDATE_GAMES_AVAILABILITY_FAILURE';

