export const CREATE_USER_ITEM_REQUEST = 'CREATE_USER_ITEM_REQUEST';
export const CREATE_USER_ITEM_SUCCESS = 'CREATE_USER_ITEM_SUCCESS';
export const CREATE_USER_ITEM_FAILURE = 'CREATE_USER_ITEM_FAILURE';

export const GET_ALL_USER_REQUEST = 'GET_ALL_USER_REQUEST';
export const GET_ALL_USER_SUCCESS = 'GET_ALL_USER_SUCCESS';
export const GET_ALL_USER_FAILURE = 'GET_ALL_USER_FAILURE';

export const DELETE_USER_ITEM_REQUEST = 'DELETE_USER_ITEM_REQUEST';
export const DELETE_USER_ITEM_SUCCESS = 'DELETE_USER_ITEM_SUCCESS';
export const DELETE_USER_ITEM_FAILURE = 'DELETE_USER_ITEM_FAILURE';

export const SEARCH_USER_ITEM_REQUEST = 'SEARCH_USER_ITEM_REQUEST';
export const SEARCH_USER_ITEM_SUCCESS = 'SEARCH_USER_ITEM_SUCCESS';
export const SEARCH_USER_ITEM_FAILURE = 'SEARCH_USER_ITEM_FAILURE';

export const UPDATE_USER_ITEMS_AVAILABILITY_REQUEST = 'UPDATE_USER_ITEMS_AVAILABILITY_REQUEST';
export const UPDATE_USER_ITEMS_AVAILABILITY_SUCCESS = 'UPDATE_USER_ITEMS_AVAILABILITY_SUCCESS';
export const UPDATE_USER_ITEMS_AVAILABILITY_FAILURE = 'UPDATE_USER_ITEMS_AVAILABILITY_FAILURE';

